#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs

sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" > /run/nginx.pid
