#!/usr/bin/env bash
#  a Bash script that displays:

# The content of the current directory uding the for loop in a list
# In a list format
# Where only the part of the name after the first dash 
# is displayed (refer to the example)


list=$(ls)
for i in $list ; do
	echo "$i" | cut -d '-' -f 2
done
